# Generated by Django 2.2.3 on 2019-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_userinfo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
