# Generated by Django 2.2.3 on 2019-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_auto_20190717_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
