# Generated by Django 2.2.3 on 2019-07-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_auto_20190717_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='token',
            new_name='authorization_token',
        ),
    ]
