# Generated by Django 2.2.3 on 2019-07-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0005_auto_20190718_2241'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user',
        ),
    ]
