# Generated by Django 2.2.3 on 2019-07-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0006_auto_20190719_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='authorization_token',
        ),
    ]
