# Generated by Django 2.2.3 on 2019-07-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='Subcategory',
        ),
    ]
