# Generated by Django 2.2.3 on 2019-08-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='bogo',
        ),
    ]
