# Generated by Django 2.2.3 on 2019-07-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
