# Generated by Django 2.2.3 on 2019-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20190720_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('₹', 'INR'), ('€', 'EURO'), ('£', 'POUND STERLING'), ('¥', 'JAPANESE YEN')], default='₹', max_length=3),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
