# Generated by Django 2.2.3 on 2019-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20190721_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('currency', models.CharField(choices=[('$', 'USD'), ('₹', 'INR'), ('€', 'EURO'), ('£', 'POUND STERLING'), ('¥', 'JAPANESE YEN')], default='₹', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
