# Generated by Django 2.2.3 on 2019-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20190722_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('₹', 'INR'), ('$', 'USD')], db_column='currency', default='₹', max_length=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=8),
        ),
    ]
