# Generated by Django 2.2.3 on 2019-07-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20190722_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
