# Generated by Django 2.2.3 on 2019-07-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20190723_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
    ]
