# Generated by Django 2.2.3 on 2019-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20190723_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
