# Generated by Django 2.2.3 on 2019-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_products_quantity_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bogo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('₹', 'INR'), ('$', 'USD')], default='₹', max_length=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
